import img from "./image/1.jpeg"
import img2 from "./image/2.jpeg"
import img3 from "./image/3.jpeg"
import img4 from "./image/4.jpeg"
import imgL5 from "./image/laptop-1.jpeg"
import imgL6 from "./image/laptop-2.jpeg"
import imgL7 from "./image/laptop-3.jpeg"
import imgL8 from "./image/laptop-4.jpeg"

const data = [
    {
        id:"phone1",
        name:"Vivo",
        company:"vivo",
        price:200000,
        color:["#ff0000","#ccc","green","pink","royalblue"],
        image:img,
        Description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus, explicabo nobis sed a autem iure voluptatem tenetur doloremque dolor architecto doloribus perferendis aspernatur quia quaerat debitis accusamus facere voluptate perspiciatis.",
        category:"Mobile",
        features:true,
        stock:"30",
        stars:"1.5",
        reviews:"58",
    },
    {
        id:"phon2",
        name:"Vivo S-3",
        company:"vivo",
        price:300000,
        color:["#ff0000","#ccc"],
        image:img2,
        Description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus, explicabo nobis sed a autem iure voluptatem tenetur doloremque dolor architecto doloribus perferendis aspernatur quia quaerat debitis accusamus facere voluptate perspiciatis.",
        category:"Mobile",
        features:true,
        stock:"30",
        stars:"3.5",
        reviews:"58",
    },
    {
        id:"phon3",
        name:"Vivo 29",
        company:"vivo",
        price:300000,
        color:["#ff0000","#ccc"],
        image:img3,
        Description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus, explicabo nobis sed a autem iure voluptatem tenetur doloremque dolor architecto doloribus perferendis aspernatur quia quaerat debitis accusamus facere voluptate perspiciatis.",
        category:"Mobile",
        features:true,
        stock:"30",
        stars:"3.5",
        reviews:"58",
    },
    {
        id:"phon4",
        name:"Vivo 29",
        company:"vivo",
        price:300000,
        color:["#ff0000","#ccc"],
        image:img4,
        Description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus, explicabo nobis sed a autem iure voluptatem tenetur doloremque dolor architecto doloribus perferendis aspernatur quia quaerat debitis accusamus facere voluptate perspiciatis.",
        category:"Mobile",
        features:false,
        stock:"30",
        stars:"3.5",
        reviews:"58",
    },
    {
        id:"laptop1",
        name:"Dell",
        company:"Dell",
        price:300000,
        color:["#ff0000","#ccc"],
        image:imgL5,
        Description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus, explicabo nobis sed a autem iure voluptatem tenetur doloremque dolor architecto doloribus perferendis aspernatur quia quaerat debitis accusamus facere voluptate perspiciatis.",
        category:"Laptop",
        features:true,
        stock:"30",
        stars:"3.5",
        reviews:"58",
    },
    {
        id:"laptop2",
        name:"Dell",
        company:"Dell",
        price:300000,
        color:["#ff0000","#ccc"],
        image:imgL6,
        Description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus, explicabo nobis sed a autem iure voluptatem tenetur doloremque dolor architecto doloribus perferendis aspernatur quia quaerat debitis accusamus facere voluptate perspiciatis.",
        category:"Laptop",
        features:false,
        stock:"30",
        stars:"3.5",
        reviews:"58",
    },
    {
        id:"laptop3",
        name:"Hp",
        company:"Hp",
        price:300000,
        color:["#ff0000","#ccc"],
        image:imgL7,
        Description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus, explicabo nobis sed a autem iure voluptatem tenetur doloremque dolor architecto doloribus perferendis aspernatur quia quaerat debitis accusamus facere voluptate perspiciatis.",
        category:"Laptop",
        features:true,
        stock:"30",
        stars:"3.5",
        reviews:"58",
    },
    {
        id:"laptop4",
        name:"Hp",
        company:"Hp",
        price:300000,
        color:["#ff0000","#ccc"],
        image:imgL8,
        Description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus, explicabo nobis sed a autem iure voluptatem tenetur doloremque dolor architecto doloribus perferendis aspernatur quia quaerat debitis accusamus facere voluptate perspiciatis.",
        category:"Laptop",
        features:false,
        stock:"30",
        stars:"3.5",
        reviews:"58",
    }
]
export default data
